spring.application.name=BilaVorona

#TelegramBot
bot.name=ArmorFlexX369Bot
bot.token=${BOT_TOKEN}

#TelegramManagerBot
manager.bot.name=ArmorFlexManagerBot
manager.bot.token=${BOT_MANAGER_TOKEN}

#DB settings
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#AI chat bot
openai.api.key=${OPENAI_API_KEY}

## Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml